# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: node -e "console.log('tag='+process.argv[1].split('.')[0])" v1.2.3 >> "$GITHUB_OUTPUT"
      id: generate-tag

    - run: echo "output = ${{ toJson(steps.generate-tag.outputs) }}"
